### PR TITLE
Global formatting

### PR DESCRIPTION
**Pull request by jenniferward**
Only worst of the formatting errors globally changed across languages. More precise formatting to follow. Things like:
****,
. **
 **
### *
** **
)[a-z]
**###
####

### CODE REVIEW

**Comment by jenniferward** [comment]
@ahankinson I had a feeling I would create conflicts by editing the same file on different branches. How do I fix it?

**Comment by ahankinson** [comment]
Conflicts generally arise because you edited an older version of a file after a newer version has been merged. 

To fix it you need to first get the newer changes from the "main" branch, and **then** make the changes you want for this branch.

There's no magic way to fix this, unfortunately. The clever way would be to try pulling from the 'main' branch into your 'formatting' branch, and then git will help you work through the conflicts.

Or you could take the loss, delete your 'formatting' branch, and then re-do these changes, splitting from the updated 'main' branch.

**Comment by ahankinson** [comment]
Give me a second -- I'll see if I can fix the conflicts

**Comment by jenniferward** [comment]
I don't mind if I just get rid of the changes on the files with the conflict, if that is possible.

**Comment by jenniferward** [comment]
Thank you!!!!

**Comment by ahankinson** [comment]
Check to see if it's fixed?

**Comment by ahankinson** [comment]
In general, it's a good idea to follow this mantra: "Pull / Branch / Commit / Push"

By pulling *before* you branch, you're guaranteed to have the latest changes. If you did "Branch / Commit / Push / Pull" then you're setting yourself up for conflicts, since you've branched on a potentially older version of the code.

**Comment by jenniferward** [comment]
Thank you! Looking back I think I did too many little steps in between, scattered across branches, without commits, so they just piled up on my side.

**Pull request merged**
