### PR TITLE
Authorities formatting complete

### PR DESCRIPTION
**Pull request by jenniferward**
This wraps up formatting for the Authorities and the Help texts.

In DE files: deleted a few dozen md files that started with "catalog_ " because they were either empty or outdated or moved to correct "publication_" file for review (indicated by >>ALT? ).

Some EN files are marked ```<jointfiles>```. These and the corresponding other language files just got random superficial formatting; we need further discussion to come up with a final format for such shared files.

The file help_figured_bass (and maybe a couple other help files) got reformatted in EN; I will leave it up to the other translators to re-edit their files.

General formatting structure is:
```
### Section 
#### Subfield
##### Examples
```
Some "source_" and "cat_" files were edited here as part of random global formatting edits. They will get more systematic editing next.

### CODE REVIEW

**Comment by ahankinson** [comment]
What do you think about using the following markup for examples:

```
<figure>
  Act 1 by Amadei, act 2 by Bononcini, overture and act 3 by Händel
  <figcaption>Example</figcaption>
</figure>
```

(You can embed HTML in Markdown)

This would replace:

```
##### Example

Act 1 by Amadei, act 2 by Bononcini, overture and act 3 by Händel
```

I'm reviewing the changes, and sometimes it's difficult to tell where the example ends and the next section starts. Using the `figure` / `figcaption` markup seems to allow for setting the example content off from the content of the body.

**Comment by jenniferward** [comment]
That's an idea! I'm not entirely happy with ```##### Example ``` because sometimes I go from ```##### Example ``` back to heading-level-4 content without officially switching headings - the example is in the middle of it. I will definitely try it!

**Comment by ahankinson** [comment]
Just did a review -- Markdown actually requires a blank line between a header and the following paragraph body, so I think those should be put back in.

I can do that if you like?

**Comment by jenniferward** [comment]
Ah ok - it made no visual difference in my md preview, and it was inconsistent, so I removed them. Yes please.  Thanks.

Following up on the HTML figure, is there a way to see how that will look in the final product? My md preview isn't giving me any visual clues (fake example follows):
image

**Comment by ahankinson** [comment]
> Following up on the HTML figure, is there a way to see how that will look in the final product? My md preview isn't giving me any visual clues

No, because we haven't yet built the final product. The styles that will be applied are not yet defined, but if we need to define something specific (like making the background colour different to anything marked in a `<figure>` block) then we can. 

If we leave it as un-marked up text, though, we can't do that.

**Comment by jenniferward** [comment]
What would the preferred style of the examples then? I can start doing that as I edit. 

```
#### Type of jurisdiction (368 $b)

Enter the type of jurisdiction associated with the institution.

<figure>
- County
- Village
  <figcaption>Examples</figcaption>
</figure>
```
I would prefer to designate it as an example at the start through, is that ok?

```
<figure>
<figcaption>Examples</figcaption>
- County
- Village
</figure>
```

And one example per block, or are multiple ok? As bullet points with ```-``` ?

**Comment by jenniferward** [comment]
Updated formatting structure:
_Note blank line after headings_

```
### Section 

First line of text.

#### Subfield or Other Important Section

First line of text.

##### Another section in rare cases

First line of text.
```

Updated examples structure:
_Note indentation of figcaption_
```
Enter the type of jurisdiction associated with the institution.

<figure>
  <figcaption>Examples</figcaption>  
  - County
  - Village
</figure>
```

**Pull request merged**
